export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const PRODUCT_QUNATITY = "PRODUCT_QUNATITY";
export const MODIFY_QUANTITY = "MODIFY_QUANTITY";
export const SUM_TOTAL_PRICE = "SUM_TOTAL_PRICE";
export const ADD_ONE_MORE_ITEM = "ADD_ONE_MORE_ITEM";
export const REMOVE_ONE_MORE_ITEM = "REMOVE_ONE_MORE_ITEM";
